### ISSUE TITLE
Automatically add opencontainers annotations to generated Docker images

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#102]
See https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys. I think we could automatically fill in a couple of values based on the data stored in the functionality.yaml.

**Comment by rcannood** [comment]
Example: https://github.com/data-intuitive/ghcr_cellranger/blob/main/src/cellranger/build_cellranger/Dockerfile#L3-L5

**Comment by rcannood** [comment]
To clarify:

* Add option for auto-detecting the `target_image_source` (e.g. https://github.com/myorg/myrepo`) to be translated into `"org.opencontainers.image.source": "https://github.com/myorg/myrepo"`
* Look for additional fields that could be filled in automatically.

**Comment by Grifs** [comment]
Implemented in Viash 0.5.13
