### ISSUE TITLE
Generate json schema from Viash CLI

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#138]
It'd be great if the reference documentation of Viash could be generated from a bunch of json files, which are in turn generated from the Viash source code itself.

Inspiration: the quarto website uses the internal [schema](https://github.com/quarto-dev/quarto-web/blob/main/docs/reference/formats/docx.json) to generate a [json](https://github.com/quarto-dev/quarto-web/blob/main/docs/reference/formats/docx.json) which in turn results in the [documentation page](https://quarto.org/docs/reference/formats/docx.html).

* [ ] Convert the content of [CLIConf](https://github.com/viash-io/viash/blob/main/src/main/scala/com/dataintuitive/viash/CLIConf.scala) to a set of json files
* [ ] Port reference documentation/schema from [website](https://viash.io/api/config/functionality/) to a place in the Viash codebase ([example](https://github.com/viash-io/viash/blob/main/src/main/scala/com/dataintuitive/viash/functionality/Functionality.scala))
* [ ] Convert the content of the internal documentation/schema to a set of json files

We might want to create subissues to track the progress of each of these tasks.

**Comment by Grifs** [comment]
Last remaining issues were added in Viash 0.5.16
