### ISSUE TITLE
Automatically detect accidentally undocumented arguments

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#232]
Some arguments of case classes are undocumented by design, as they are for internal usage only.

It would be great if we could add a tag to explicitly denote that this is the case, e.g.:
```scala
@internal
dummy_arguments: List[Argument[_]] = Nil
```

Futhermore, we should then be able to check which case classes have undocumented arguments in their constructor, either through reflection or regex pattern matching, to be able to detect and fix missing entries in the reference documentation on viash.io.

**Comment by Grifs** [comment]
Implemented in Viash 0.6.3
