### ISSUE TITLE
Check whether all documented deprecated functionality throws warnings when used.

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#266]
Several arguments which were documented as deprecated (e.g. `apk`, `apt`) did not throw warning messages when used until #265. It'd be a good idea to manually verify that currently deprecated features to see if they indeed generate warnings.

**Comment by rcannood** [comment]
@Grifs This is solved, right?

**Comment by Grifs** [comment]
Deprecation messages are auto generated since Viash 0.6.7
