### ISSUE TITLE
`viash_push` wrongly reports a container does not exist in the container repo

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#290]
When running `viash_push` on a container that is already present in the repository with the exact same tag, it should report that that container already exists and not overwrite it. A `--force` argument can be added to `viash_push` to overwrite it.

This is what I notice for a container that certainly already exists:

```sh
$ bin/viash_push -m release -t main_build -q process_samplesubmissionfile
In RELEASE mode with tag 'main_build'.
Exporting process_samplesubmissionfile (io_processing) =docker=> target/docker/io_processing/process_samplesubmissionfile
[notice] Container '<repo>/htrnaseq/io_processing/process_samplesubmissionfile:main_build' does not yet exist.
[notice] Pushing image to <repo>/htrnaseq/io_processing/process_samplesubmissionfile:main_build'
```

**Comment by Grifs** [comment]
`viash_push` was removed in Viash 0.7.5, so closing this issue as it is no longer relevant.
