### ISSUE TITLE
Refactor config mods

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#292]
There's something wrong with the config mods, because the following test is failing:

```scala
  val baseJson: Json = parse(
    """foo: bar
      |baz: 123
      |list_of_stuff: [4, 5, 6]
      |""".stripMargin).right.get

  test("test condition and") {
    val cmd4 = ConfigModParser.condition.parse(""".foo == "ping" && false"""")
    val res4 = cmd4.apply(baseJson)
    assert(res4 == false) // false && false
  }
```

Looking at the code for the config mods, it makes sense that this error would be thrown. I'll rewrite part of the config mod parsing, something which I've started in the branch [`refactor_parsing`](https://github.com/viash-io/viash/tree/refactor_parsing).

**Comment by Grifs** [comment]
Solved in Viash 0.7.2
