### ISSUE TITLE
Be able to document environment variables that Viash listens to, i.e. VIASH_VERSION and VIASH_HOME.

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#306]
From #304

**Comment by Grifs** [comment]
One way of solving this could be to add additional classes solely used for documentation.
With reflection we could search for all classes of the given documentation class.

This would also be a great benefit for the config schema exports.

However, with Scala 2 reflection is not powerful enough. I believe this is vastly improved in Scala 3.

**Comment by Grifs** [comment]
Added under config.environmentVariables in Viash 0.7.5
