### ISSUE TITLE
Docker platform features require 'experimental features' in Docker

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#31]
When you use `--push` with viash in combination with a valid registry (`target_registry` attribute in the Docker platform) viash uses `docker manifest inspect` internally to check if an image already exists. The latter is only available if Docker _experimental features_ are configured.

This is only valid for a viash version that contains the Docker push functionality (v0.4.0 and above) and only manifests itself when using the default push strategy.

**Comment by tverbeiren** [comment]
The solution is to configure Docker to use [experimental features](https://docs.docker.com/engine/reference/commandline/cli/#experimental-features). One way to do that is to add the following to `~/.docker/config.json`:

```
	"experimental": "enabled"
```

In the future we will add a check in viash to see if this configuration is set and provide a warning to the user.

**Comment by rcannood** [comment]
Can we consider this as solved, then?

**Comment by tverbeiren** [comment]
Yes!

**Comment by Grifs** [comment]
Closing this as the issue hasn't been present for quite some time now
