### ISSUE TITLE
Add ability to add custom config for nextflow VDSL3 components during build

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#385]
Currently, when building VDSL3 components, a default `nextflow.config` is added to the build component. It would be handy to allow extending this functionality by allowing adding extra configuration from the viash config (e.g. at `platform` -> `nextflow`)

**Comment by DriesSchaumont** [comment]
Added bonus: this would also allow per-component nextflow configuration to be added.

**Comment by Grifs** [comment]
Related to #415

**Comment by Grifs** [comment]
Implemented in Viash 0.7.4
