### ISSUE TITLE
Viash should not use colorized output in non-TTY shells

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#394]
A warning like this does not make a lot of sense:

```
[31mReading file '<...>/config.vsh.yaml' failed[0m
```

This happens in different situations, generating documentation for instance. Viash should be better aware of the context it's running in.

Viash [uses explicit ANSI colors](https://github.com/viash-io/viash/blob/main/src/main/scala/io/viash/config/Config.scala#L241-L244) in lines like this:

```scala
def parsingErrorHandler[C](e: Exception): C = {
  Console.err.println(s"${Console.RED}Error parsing '${uri}'.${Console.RESET}\nDetails:")
  throw e
}
```

This should be made conditional on whether we want to use colors or not, or in other words whether it's running in a TTY or not. The problem is that there does not seem to be a canonical way to check if a TTY is available or not.

The alternative could be setting an environment variable that is read by Viash to decide if ANSI colors should be added or not.

**Comment by Grifs** [comment]
Implemented in Viash 0.7.5
