### ISSUE TITLE
See if the `entrypoint` argument can be removed

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#409]
The NextflowScript has an `entrypoint` argument. However, all of the Scripts also have an `entrypoint` argument which, in those cases, should not be used:

```
  @undocumented
  entrypoint: Option[String] = None,
...
assert(entrypoint.isEmpty, message = s"Entrypoints are not (yet) supported for resources of type ${`type`}.")
```

If this argument could be removed, that'd be great!

**Comment by Grifs** [comment]
Solved in Viash 0.7.4
