### ISSUE TITLE
Reduce stack trace

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#434]
_Transferred from openproblems-bio/openproblems-v2#121_

> ### Long and confusing error message on config parse failure
> This should be a short and simple error message, instead it's 50 lines including a link to github issues and a deep stack trace.
> 
> ```
> ✗ viash test src/label_projection/methods/scanvi_xgboost/config.vsh.yaml
> Unexpected error occurred! If you think this is a bug, please post
> create an issue at https://github.com/viash-io/viash/issues containing
> a reproducible example and the stack trace below.
> 
> viash - 0.7.0
> Stacktrace:
> java.lang.RuntimeException: Type float is not recognised. Valid types are string, integer, long, double, boolean, boolean_true, boolean_false and file.
>         at io.viash.functionality.arguments.package$.$anonfun$decodeDataArgument$1(package.scala:126)
>         at io.circe.Decoder$$anon$16.apply(Decoder.scala:493)
>         at io.circe.SeqDecoder.apply(SeqDecoder.scala:17)
>         at io.circe.Decoder.tryDecode(Decoder.scala:70)
>         at io.circe.Decoder.tryDecode$(Decoder.scala:69)
>         at io.circe.SeqDecoder.tryDecode(SeqDecoder.scala:6)
>         at io.circe.generic.extras.decoding.ReprDecoder.orDefault(ReprDecoder.scala:47)
>         at io.viash.functionality.package$anon$lazy$macro$119$1$$anon$2.configuredDecode(package.scala:37)
>         at io.circe.generic.extras.decoding.ConfiguredDecoder$NonStrictCaseClassConfiguredDecoder.apply(ConfiguredDecoder.scala:81)
>         at io.circe.Decoder$$anon$7.$anonfun$apply$5(Decoder.scala:214)
>         at scala.Option.getOrElse(Option.scala:201)
>         at io.circe.Decoder$$anon$7.apply(Decoder.scala:214)
>         at io.circe.generic.extras.decoding.ConfiguredDecoder$StrictCaseClassConfiguredDecoder.apply(ConfiguredDecoder.scala:122)
>         at io.circe.Decoder.tryDecode(Decoder.scala:70)
>         at io.circe.Decoder.tryDecode$(Decoder.scala:69)
>         at io.circe.generic.decoding.DerivedDecoder.tryDecode(DerivedDecoder.scala:6)
>         at io.circe.Decoder$$anon$11.tryDecode(Decoder.scala:300)
>         at io.circe.generic.extras.decoding.ReprDecoder.orDefault(ReprDecoder.scala:47)
>         at io.viash.config.package$anon$lazy$macro$31$1$$anon$2.configuredDecode(package.scala:31)
>         at io.circe.generic.extras.decoding.ConfiguredDecoder$NonStrictCaseClassConfiguredDecoder.apply(ConfiguredDecoder.scala:81)
>         at io.circe.Decoder.tryDecode(Decoder.scala:70)
>         at io.circe.Decoder.tryDecode$(Decoder.scala:69)
>         at io.circe.generic.decoding.DerivedDecoder.tryDecode(DerivedDecoder.scala:6)
>         at io.circe.Decoder$$anon$11.tryDecode(Decoder.scala:300)
>         at io.circe.Decoder$$anon$11.apply(Decoder.scala:299)
>         at io.circe.Json.as(Json.scala:107)
>         at io.viash.config.Config$.readFromUri(Config.scala:260)
>         at io.viash.config.Config$.read(Config.scala:226)
>         at io.viash.Main$.readConfig(Main.scala:351)
>         at io.viash.Main$.mainCLI(Main.scala:220)
>         at io.viash.Main$.mainCLIOrVersioned(Main.scala:117)
>         at io.viash.Main$.main(Main.scala:64)
>         at io.viash.Main.main(Main.scala)
> ```

**Comment by Grifs** [comment]
Fixed in Viash 0.7.5
