### ISSUE TITLE
Invalid numeric string -.inf

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#445]
Viash is not able to process Viash configs with `+.inf`, `-.inf` or `.nan` as values, despite this being valid YAML notation: https://yaml.org/type/float.html

Example:

`config.vsh.yaml`:

```yaml
functionality:
  name: foo
  info:
    min: -.inf
    max: +.inf
    nan: .NaN
```

```bash
viash config view config.vsh.yaml
```

      viash: Error parsing, invalid Yaml structure in file 'file:config.vsh.yaml'.
      Details:
      Invalid numeric string -.inf

**Comment by Grifs** [comment]
Fixed in Viash 0.7.5
