### ISSUE TITLE
`--help` should take precedence

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#449]
Let's assume this scenario: a viash user wants to execute `viash ns list`. The user starts to type the command and adds the first argument:

```
viash ns list -q concat
```

Then, the user would like to apply a second argument, but does not remember it. So, the user adds `--help` at the end in order to easily remove it afterwards

```
viash ns list -q concat --help
```

However, the result is that the command gets executed instead of showing the usage information.
I would think that `--help` is never ignored.

**Comment by Grifs** [comment]
Implemented in Viash 0.7.5

**Comment by Grifs** [comment]
Implemented in Viash 0.7.5
