### ISSUE TITLE
Refactor getting and setting envs

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#455]
Instead of directly interfacing with the environment variables, it'd be useful to have a higher level wrapper around this functionality, which also allows specifying the defaults in a convenient manner. This could then be used to also document the environment variables used by Viash.

**Comment by Grifs** [comment]
Strongly related to #306

**Comment by Grifs** [comment]
Implemented in Viash 0.7.5

**Comment by Grifs** [comment]
Implemented in Viash 0.7.5
