### ISSUE TITLE
Feature request: Reuse old dependencies for viash test

### ISSUE THREAD

**Issue by mumichae** [viash-io/viash#495]
Having viash reinstall dependencies for each test run by default is a great idea. However, when fixing small things (e.g. syntax errors), it would be good to have an option to reuse a successfully installed viash environment instead of having to reinstall them. This could be flag on the command line e.g.

```
viash test config.vsh.yaml --reuse_environment
```

**Comment by Grifs** [comment]
Hi Michaela,

For the next release we have already added the functionality to specify the [`--setup` strategy](https://viash.io/guide/component/add-dependencies.html#step-3-rebuild-docker-image) like it was available with `viash build`.
This would allow to run
```
viash test config.vsh.yaml --setup cachedbuild
```
or
```
viash test config.vsh.yaml --setup ifneedbebuild
```

While this quite related and might ultimately solve your use case, I'm a bit wondering what I'm missing as the default behaviour is already `cachedbuild`. This should for the most part cutout most of the rebuilding of docker containers.

Would it be possible to share your use case in more detail? Maybe we can identify a shortcoming somewhere or verify that the upcoming functionality resolves your use case too.

Thanks!

**Comment by rcannood** [comment]
@mumichae Is this a solution to the problem you're having? :relaxed:

**Comment by mumichae** [comment]
Thanks, this helped!
