### ISSUE TITLE
Namespace test inconsistent behaviour towards temporary folders

### ISSUE THREAD

**Issue by Grifs** [viash-io/viash#51]
Namespace tests runs each test in a separate temporary folder instead of having one temporary folder and recreating the folder structure of the namespace.
Additionally, the temporary folders are not printed on the console.
If `--keep true` is specified, the folders will be kept but it is left to the user to search which folders are located where.

It would be beneficial to have a single folder that contains all test artifacts and have that folder be printed on the console.
An intermediate solution could be to have an option so that the log output displays an extra step showing the path to each test.

**Comment by rcannood** [comment]
:+1: thanks for solving this!
