### ISSUE TITLE
VDSL3: Set `simplifyOutput` to `false`

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#522]
@tverbeiren Can we set this default to `false`? I don't like it when components behave differently depending on how many outputs the component has.

You can always set the default back to true with:

```
config_mods: |
  .platforms[.type == 'nextflow'].auto.simplifyOutput := true
```

**Comment by tverbeiren** [comment]
Yes!

**Comment by rcannood** [comment]
I'm not going to let grass grow over that!
