### ISSUE TITLE
Expand Viash Project Config format and functionality

### ISSUE THREAD

**Issue by Grifs** [viash-io/viash#596]
Define additional fields that are now often defined via config mods, e.g. `version`.

During `ns build` , use these fields to set values in the component configs.

Additionally, store the used Viash Project in the built config output. TBD. directly under the config root or under the `info` field.
Additionally 2, store used config mods or other build settings from the command line into the built config output.

**Comment by rcannood** [comment]
These are some of the fields I think we'll need:

```scala
case class ViashProject(
  name: String,
  version: String,
  description: String,
  info: Json,
  config_mods: List[String],
  repositories: List[Repository],
  viash_version: String
)
```

(Some of these types should be Optional)

**Comment by Grifs** [comment]
> > During ns build , use these fields to set values in the component configs.
> 
> Do you propose:
> 
> 1. Using this ViashProject (name TBD) and simply store it in the viashconfig so the relevant code can access it later
> 2. Would you propose modifying the Config using the fields present in the ProjectConfig?
> 3. Translating each of the values in the ViashProject into a set of config mods?

I'd say option 2.
Question is how precedense is of these values if both it is set in both the component config and project config.
Probably it also depends on the value type: 

- if it's a single value; prefer the value from the component or project config? (e.g. version)
- if it's a list; prepend the project config to the component config? (e.g. repositories)

> 
> > Additionally, store the used Viash Project in the built config output. TBD. directly under the config root or under the info field.
> 
> And in the `.build.yaml`?

Good idea!

**Comment by rcannood** [comment]
> I'd say option 2.

Ok to me!

> Question is how precedense is of these values if both it is set in both the component config and project config.
Probably it also depends on the value type:

You mention that it will also depend on the data itself.

**Comment by Grifs** [comment]
Discussion continued in #612 and will be added in Viash 0.9.0
