### ISSUE TITLE
Add Community guidelines

### ISSUE THREAD

**Issue by abhishektiwari** [viash-io/viash#598]
Add clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

For [JOSS Review] (https://github.com/openjournals/joss-reviews/issues/6089)

**Comment by rcannood** [comment]
@abhishektiwari Thanks for your very positive review and proposed changes! We'll go through your suggestions and make the necessary changes.

**Comment by rcannood** [comment]
Contributing guidelines were added in #600 and merged into the main branch with the release of Viash 0.8.2. Thanks @abhishektiwari !
