### ISSUE TITLE
[FEATURE] Raise an error when an R package can't be installed in a container setup

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#629]
### Feature summary

When an R package can not be installed using `install.packages` it generates a warning rather than an error. Consequently the container build continues but is not complete.

### Feature description

When installing an R package using `install.packages`, something like this can happen:

```
> install.packages("...", type = "source", repos = NULL, verbose = TRUE, dependencies = TRUE)
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
system (cmd0): /usr/local/lib/R/bin/R CMD INSTALL
* installing *source* package ‘...’ ...
...
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called ‘???’
...
Warning message:
In install.packages("...", type = "source",  :
  installation of package ‘...’ had non-zero exit status
```

The installation error should raise an error rather than a wanring. This would give immediate feedback to the developer or later during CI builds that something is wrong.

### Why is this feature beneficial?

There's a lot of benefit in being sure that if a container builds, it means all dependencies are available.

### Possible solution

Something like the function described here could help: https://stackoverflow.com/a/73534778

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate request.
- [X] I have provided clear and concise information about the feature.

**Comment by Grifs** [comment]
Implemented in #771
