### ISSUE TITLE
Output files from NextFlow processes running in Docker are owned by root

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/viash#66]
When you use the Docker platform with viash, a default attribute `chown: true` is implicit which means the output is `chown`d to your normal user rather than the (root) user running in the container.

With NextFlow this viash functionality can not be used because NexrtFlow handles the starting of the container for us and we simply run the viash native binary. As a result all output files are owned by `root`.

**Comment by tverbeiren** [comment]
A simple solution is to use this in the `nextflow.config`:

```
docker.fixOwnership = true
```

Which will do a `chown` at the end of every process on all outputs.

**Comment by tverbeiren** [comment]
This will be added to the default `nextflow.config` file.

**Comment by tverbeiren** [comment]
@rcannood This can be closed, I guess?

**Comment by rcannood** [comment]
:+1: !

**Comment by rcannood** [comment]
Syke!
