### ISSUE TITLE
[FEATURE] Implement `auto: [publish: true]` for workflows

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#664]
### Feature summary

Implement `auto: [publish: true]` for workflows

### Feature description

Allows publishing the output from a workflow (that is used as a subworkflow) based on the workflow viash config (`file` arguments with `direction: output`).

### Why is this feature beneficial?

- Feature pairing with regular components
- Avoids needing to implement custom publish components

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate request.
- [X] I have provided clear and concise information about the feature.

**Comment by rcannood** [comment]
We have `auto: [publish: "state"]` for this -- that's what `publish: state` was for.

**Comment by rcannood** [comment]
@DriesSchaumont Can I close this PR?

**Comment by DriesSchaumont** [comment]
Yes, closing as this is implemented. Other issues should probably be tracked in separate tickets (like #615)
