### ISSUE TITLE
[BUG] Arguments missing from schema

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#742]
### What happened?

`arguments` appears to be missing from the config json schema

### Steps to reproduce

```bash
viash export json_schema
```

### Expected behavior

defining arguments should be allowed

### Version

Viash 0.9.0-RC6

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.

**Comment by Grifs** [comment]
Fixed in Viash 0.9.0-RC7
