### ISSUE TITLE
Update openjdk base image in viash dockerfile

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#745]
https://github.com/viash-io/viash/blob/0244919c15e3495c9f0b56c7f53dd0c3dc5ae1ab/Dockerfile#L1

**Comment by Grifs** [comment]
I'd say, certainly not 18 either. 11, 17, 21 would make a lot of sense though.

**Comment by rcannood** [comment]
Good point. My apologies for the short github issue. I was trying to run `make docker` and found that it no longer works.

**Comment by Grifs** [comment]
Updated in Viash 0.9.0-RC7
