### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#77]
I'm getting tired of creating separate issues for them. Here's an issue to track multiple small issues.

- [x] Allow specifying the destination path of text-based resources using the 'path' attribute instead of the 'dest' attribute.
      Current: `[ text: "Foo", dest: "file.txt" ]`. 
      Proposed: `[ text: "Foo", path: "file.txt" ]`.
- [x] Text-based scripts should have a default path.
      Current: `[ type: "r_script", text: "print(par)", dest: "script.R" ]`. 
      Proposed: `[ type: "r_script", text: "print(par)" ]`.
- [x] Change temporary directory defaults.
      Current: If `VIASH_TEMP` is not set, use `/tmp`.
      Proposed: If `VIASH_TEMP` is not set, first take a look at alternatives such as `TMPDIR`, `TMP`, ... or else `/tmp`.
- [x] Don't add the RESOURCES_DIR to the PATH. It's completely unnecessary and might cause naming conflicts between existing commands that are on the path. 
    Current: `PATH="$VIASH_RESOURCES_DIR:$PATH"` ([link](https://github.com/viash-io/viash/blob/e1a6d02841370b22ec2f119ebb176c3c680d722e/src/main/scala/com/dataintuitive/viash/wrapper/BashWrapper.scala#L95))
    Proposed: Don't add the resources dir to the PATH.
- [x] Allow disabling components such that they don't get picked up by `viash ns`.
    Current: Rename `config.vsh.yaml` to `config.novsh.yaml`.
    Proposed: Add a field `.functionality.enabled` to the config, which can be set to false.
- [x] Turn viash bootstrapper into a native component
    Current: This component uses a Docker backend. Because of this, the default viash installations don't work inside of a Docker container without using Docker in Docker.
    Proposed: Make the component use the native platform and generate an understandable error message when some tools (like 'fetch', 'make' or 'sbt') are needed but not available.
 - [x] Rename viash_bootstrap to viash_install
 - [x] Allow detecting viash code blocks with indents:
      Current:
      ```scala
      object Main extends App {
      // VIASH START
          case class ViashPar(
              inputfile: String,
              domain: String
          )
      
          val par = ViashPar(
              inputfile = "Testfile.md",
              domain = "https://viash.io"
          )
      // VIASH END
      }
      ```
      Desired:
      ```scala
      object Main extends App {
          // VIASH START
          case class ViashPar(
              inputfile: String,
              domain: String
          )
      
          val par = ViashPar(
              inputfile = "Testfile.md",
              domain = "https://viash.io"
          )
          // VIASH END
      }
      ```

**Comment by DriesSchaumont** [comment]
- [ ] Another feature that could be helpful is a way to indicate the 'status' of a component in a viash config (as an extension of enabled/disabled): provide a deprecation warning (deprecated), in development, active, disabled, soon to be deprecated, ...

**Comment by Grifs** [comment]
- [ ] Add overview result for `viash ns build` with X amount failed & Y amount successfully built

**Comment by rcannood** [comment]
I created a new issue for Dries' comment. Afaik this issue can be closed now.

**Comment by Grifs** [comment]
Closing issue/tasks for now. If needed we can create a new issue with multiple tasks.
