### ISSUE TITLE
How to install viash into a docker image?

### ISSUE THREAD

**Issue by hhuuggoo** [viash-io/viash#84]
Hi, I'm following the [installation instructions](https://viash.io/docs/getting_started/installation/), and was attempting to run them during the build of a Docker image - but it errored out because it seems the installation depends on docker?

Is the proper way to do this, just to lift the necessary steps out of [the Dockerifle?](https://github.com/viash-io/viash/blob/main/Dockerfile)

**Comment by rcannood** [comment]
Hey @hhuuggoo !

I think the easiest way to install viash is to take any docker container that contains bash and java, and run something like `wget https://github.com/viash-io/viash/releases/download/0.5.1/viash -O /usr/bin/viash`.

Is this what you were looking for?

Kind regards,
Robrecht

**Comment by hhuuggoo** [comment]
Yes, thank you!
